language:
 - cpp
compiler:
 - gcc
 - clang
sudo: required
dist: trusty

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev libqt5webkit5-dev
 - sudo apt-get install -qq libcv-dev libcvaux-dev libhighgui-dev libopencv-dev libjpeg-dev libpng-dev

before_script:
 - mkdir build
 - cd build
 - cmake ..
script:
 - make
