language:
- cpp
compiler:
- gcc
- clang
install:
- sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
- sudo add-apt-repository ppa:smspillaz/cmake-2.8.12 -y
- sudo apt-get update -qq
- sudo apt-get purge cmake -qq
- sudo apt-get install -y -qq cmake
- sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev qttools5-dev libqt5webkit5-dev
- sudo apt-get install -qq libcv-dev libcvaux-dev libhighgui-dev libopencv-dev

before_script:
- mkdir build
- cd build
- cmake ..
script: make
