version: "{build}"

skip_non_tags: true

clone_folder: c:\projects\lenna
image:
  - Visual Studio 2017
configuration:
  - Release
platform:
  - x64
environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
      ARCHITECTURE: "-A x64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.13.2\msvc2017_64
      PLATFORM: x64
      OPENCV_VERSION: 4.5.0
matrix:
  fast_finish: true

install:
  - set PATH=%QTDIR%\bin;%PATH%
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - cmd: choco install opencv -y --version=%OPENCV_VERSION%

before_build:
  - IF EXIST c:\tools\opencv* CD c:\tools\opencv*
  - SET OPENCV_DIR=%CD%\build
  - SET OpenCV_DIR=%CD%\build
  - set QT_DIR=%QTDIR%
  - set Qt5_DIR=%QTDIR%\lib\cmake\Qt5
  - cd c:\projects\lenna
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -DOPTION_SELF_CONTAINED=ON "-G%GENERATOR%" %ARCHITECTURE%
build:
  project: c:\projects\lenna\build\lenna.sln
  verbosity: minimal
  parallel: true

after_build:
  - cmd: |-
      cd c:\projects\lenna\build
      cmake --build . --target pack
      dir

only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - source/
    - cmake/

artifacts:
  - path: 'build\Release\lenna.exe'
  - path: 'build\*.exe'
    name: installer
  - path: 'build\*.zip'

deploy:
  - provider: GitHub
    auth_token:
      secure: qgNDEr0uvXPJrujCdr3B45ibV7Llee5FrFthLvHOLE0h+i1x50XEZzdnAh7omZdC
    artifact: installer
    draft: false
    prerelease: false
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    force_update: true
    on:
      APPVEYOR_REPO_TAG: true
